#!/bin/sh
# ODd Fetch
exec 3>/dev/null
RESET="$(printf '\033[0m\033[39m\033[49m')"

# Fallback colors and logo
ODFC1="$(printf '\033[1;34m')" # blue
ODFC2="$(printf '\033[0;37m')" # white
ODFLOGO="${C1}   /\\
  /  \\
 /____\\
  ${C2}  ||
    ||${RESET}"
ID=linux
PRETTY_NAME=Linux
if [ -n "$ODFCTRL" ]; then
  exec 3>&2
  if [ "$1" = "upd" ]; then
    [ "$(id -u)" -eq 0 ] || { echo "Must be run as root." >&2; exit 1; }
    /usr/share/odf/update.sh
    exit
  elif [ "$1" = "uninst" ]; then
    [ "$(id -u)" -eq 0 ] || { echo "Must be run as root." >&2; exit 1; }
    /usr/share/odf/uninstall.sh
    exit
  fi
fi
if [ "$1" = "sh" ]; then
  PS1="odf$ " ODFCTRL="yep" exec sh
fi
# Source configs
if [ -f "/etc/os-release" ]; then
  while IFS='=' read -r key val; do
    eval "$key=\$val"
  done < /etc/os-release
fi;if [ -f "/usr/share/odf/logos/$ID" ]; then
  . "/usr/share/odf/logos/$ID"
fi;if [ -f ~/.config/odf.sh ]; then
 . ~/.config/odf.sh
fi;if [ -n "$1" ]; then
 ODFST=
 . "$1"
fi

USERHOST="$(whoami)@$(cat /etc/hostname)"
KERNEL="$(uname -r)"
UPTIME="$(uptime -p | sed 's/^up //')"
# Thanks Dylan Araps! I took this from pfetch, but made a lot of changes to it.
has() {
  _cmd=$(command -v "$1") 2>&3 || return 1
  [ -x "$_cmd" ] || return 1
}
get_pkgs() {
  packages=$(
    has bonsai     && bonsai list 2>&3
    has crux       && pkginfo -i 2>&3
    has pacman-key && pacman -Qq 2>&3
    has dpkg       && dpkg-query -f '.\n' -W 2>&3
    has rpm        && rpm -qa 2>&3
    has xbps-query && xbps-query -l 2>&3
    has apk        && apk info 2>&3
    has guix       && guix package --list-installed 2>&3
    has opkg       && opkg list-installed 2>&3
    has kiss       && printf '%s\n' /var/db/kiss/installed/*/ 2>&3
    has cpt-list   && printf '%s\n' /var/db/cpt/installed/*/ 2>&3
    has brew       && printf '%s\n' "$(brew --cellar)/"* 2>&3
    has emerge     && printf '%s\n' /var/db/pkg/*/*/ 2>&3
    has pkgtool    && printf '%s\n' /var/log/packages/* 2>&3
    has eopkg      && printf '%s\n' /var/lib/eopkg/package/* 2>&3
    has nix-store  && {
      nix-store -q --requisites /run/current-system/sw 2>&3
      nix-store -q --requisites ~/.nix-profile 2>&3
    }
  )
  packages=${packages#"${packages%%[![:space:]]*}"}
  packages=${packages%"${packages##*[![:space:]]}"}
   echo $packages | wc -w
#  case $packages in
#    (1?*|[2-9]*)
#       echo "$packages"
#    ;;
#  esac
}
INFO="$(cat <<EOF
${RESET}${ODFC1}$USERHOST${RESET}
${RESET}${ODFC2}OS:${RESET}     $(echo $PRETTY_NAME|sed 's/^"\(.*\)"$/\1/')
${RESET}${ODFC2}Kernel:${RESET} $KERNEL
${RESET}${ODFC2}Uptime:${RESET} $UPTIME
${RESET}${ODFC2}Pkgs:${RESET}   $(get_pkgs)
${ODFST}
EOF
)"

if [ -n "$ODFUD" ]; then
  echo "$ODFLOGO"
  echo "$INFO"
else
  paste <(printf "%s\n" "$ODFLOGO") <(printf "%s\n" "$INFO")
fi
